In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, KFold

In [30]:
# Load the data
train_data = pd.read_csv('Encoded_Train.csv')
# train_data.drop('w', axis=1, inplace=True)
test_data = pd.read_csv('Encoded_Test.csv')

In [31]:
# Define features and target
X_train = train_data.drop('y', axis=1)
y_train = train_data['y']

In [32]:
# Normalize the feature data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(test_data)

In [33]:
train_data.head()

,y,square_meters,bathrooms_number,lift,rooms_number,total_floors_in_building,availability,condominium_fees,year_of_construction,conditions,...,zone_villa san giovanni,zone_vincenzo monti,zone_washington,zone_zara,zone_corso magenta,zone_largo caioroli 2,"zone_via marignano, 3",zone_cascina gobba,zone_scala - manzoni,zone_via fra' cristoforo
0,1125000,135,2.0,1.0,3,7.0,20230101.0,417.0,1929.4,1.0,...,0,0,0,0,0,0,0,0,0,0
1,500000,57,1.0,1.0,2,7.0,20230101.0,0.0,2010.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2,395000,92,1.0,1.0,3,8.0,20230101.0,200.0,1960.0,1.0,...,0,0,0,0,0,0,0,0,0,0
3,340000,63,1.0,0.0,2,8.0,20246959.5,208.0,1929.4,1.0,...,0,0,0,0,0,0,0,0,0,0
4,199000,38,1.0,0.0,1,4.0,20230101.0,80.0,1930.0,1.0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
test_data.head()

,square_meters,bathrooms_number,lift,rooms_number,total_floors_in_building,availability,condominium_fees,year_of_construction,conditions,floor,...,zone_villa san giovanni,zone_vincenzo monti,zone_washington,zone_zara,zone_corso magenta,zone_largo caioroli 2,"zone_via marignano, 3",zone_cascina gobba,zone_scala - manzoni,zone_via fra' cristoforo
0,112,1.0,1.0,3,6.0,20200315.0,250.0,1965.0,3.0,2.0,...,0,0,0,0,0,0,0,0,0,0
1,180,3.0,1.0,5,7.0,20200315.0,410.0,1960.0,1.0,4.0,...,0,0,0,0,0,0,0,0,0,0
2,92,2.0,1.0,2,5.0,20200315.0,500.0,1940.0,1.0,5.0,...,0,0,0,0,0,0,0,0,0,0
3,61,1.0,1.0,2,5.0,20246959.5,100.0,1900.0,3.0,2.0,...,0,0,0,0,0,0,0,0,0,0
4,130,2.0,1.0,3,8.0,20200315.0,308.0,1970.0,3.0,4.0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
# parameters choice
parameters = { 'objective': ['reg:tweedie'], 'enable_categorical': [True], 'random_state':[88], 'max_depth': [5], 
               'min_child_weight': [0], 'subsample': [0.66], 'colsample_bytree': [0.235], 'learning_rate': [0.02], 
               'n_estimators': [16000], 'lambda': [0.0], 'alpha': [0.2], 'gamma': [0.4], 'validate_parameters': [True],
               'tree_method': ['hist'], 'max_leaves': [200], 'booster': ['gbtree']}

model = xgb.XGBRegressor(**parameters)

kfold = KFold(n_splits = 10, shuffle = True, random_state = 88)
grid_search = GridSearchCV(estimator = model, param_grid = parameters, cv = kfold, scoring = 'neg_mean_absolute_error', n_jobs = -1, verbose = 2)
grid_search.fit(X_train_scaled, y_train)

y_pred = grid_search.predict(X_test_scaled)

Fitting 10 folds for each of 1 candidates, totalling 10 fits

In [36]:
# Save predictions to a text file
with open('predictions.txt', 'w') as f:
    for pred in y_pred:
        f.write(f"{pred}\n")